# Tarea 01 — Python y NumPy

**Instrucciones:** Completa cada celda de código con tu respuesta. No modifiques las celdas de texto.  
Cada pregunta indica exactamente qué debes escribir.

---
## Parte 1 — Python básico

**P1.** Crea una variable llamada `nombre` con tu nombre, y otra llamada `edad` con tu edad.  
Luego imprime el mensaje: `Hola, me llamo Ana y tengo 22 años.` (con tus datos).

In [10]:
# Tu respuesta aquí
nombre = "Juan Pablo"
edad = 31
print(f'Hola, me llamo {nombre} y tengo {edad} años')

Hola, me llamo Juan Pablo y tengo 31 años


**P2.** Dada la lista `numeros = [10, 25, 3, 47, 8, 15]`:  
- Imprime el primer y el último elemento.  
- Imprime los tres primeros elementos usando slicing.  
- Agrega el número `99` al final de la lista.

In [11]:
numeros = [10, 25, 3, 47, 8, 15]

# Tu respuesta aquí
print(numeros[0],",",numeros[-1])
print(numeros[0:3])
numeros.append(99)
print(numeros)

10 , 15
[10, 25, 3]
[10, 25, 3, 47, 8, 15, 99]


**P3.** Dado el diccionario `estudiante` con las llaves `nombre`, `carrera` y `promedio`,  
escribe un `if` que imprima `"Aprobado"` si el promedio es mayor o igual a 6, y `"Reprobado"` si no.

In [14]:
estudiante = {"nombre": "Carlos", "carrera": "Sistemas", "promedio": 7.5}

# Tu respuesta aquí
if estudiante['promedio']>= 6:
  print('Aprobado')
else:
    print('reprobado')


Aprobado


**P4.** Crea una función llamada `calcular_area` que reciba `base` y `altura` y devuelva el área de un triángulo (`base * altura / 2`).  
Llama la función con `base=5` y `altura=8` e imprime el resultado.

In [18]:
# Tu respuesta aquí
def calcular_area(base, altura):
  area = (base * altura / 2)
  return area

triangulo = calcular_area(5, 8)
print(triangulo)

20.0


**P5.** Usa una **list comprehension** para crear una lista con los cuadrados de los números del 1 al 10.  
Imprime la lista resultante.

In [25]:
# Tu respuesta aquí
cuadrados = [x**2 for x in range(1, 11)]
print(cuadrados)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


---
## Parte 2 — NumPy

In [26]:
import numpy as np

**P6.** Crea los siguientes arreglos e imprime su `shape` y `dtype`:  
- Un arreglo con los valores `[1.5, 2.5, 3.5, 4.5]`  
- Una matriz de ceros de 3 filas × 4 columnas  
- Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando `linspace`)

In [48]:
# Tu respuesta aquí
# Un arreglo con los valores [1.5, 2.5, 3.5, 4.5]
valores = (1.5, 2.5, 3.5, 4.5)
np_valores = np.array(valores)
print(np_valores)
print("Shape:", np_valores.shape)
print("Type:", np_valores.dtype)

print('-------')
#Una matriz de ceros de 3 filas × 4 columnas
matriz = np.zeros((3,4))
print(matriz)
print("Shape:", matriz.shape)
print("Type:", matriz.dtype)
print('-------')

#Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando linspace)
arreglo = np.linspace(0,1,6)
print(arreglo)
print("Shape:", arreglo.shape)
print("Type:", arreglo.dtype)

[1.5 2.5 3.5 4.5]
Shape: (4,)
Type: float64
-------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)
Type: float64
-------
[0.  0.2 0.4 0.6 0.8 1. ]
Shape: (6,)
Type: float64


**P7.** Dado el arreglo `a = np.arange(1, 13)`, usa `reshape` para convertirlo en una matriz de 3 × 4.  
Luego imprime el valor máximo, el valor mínimo y la posición (índice) del máximo.

In [67]:
a = np.arange(1, 13)

# Tu respuesta aquí
matriz = a.reshape(3,4)
valor_max = matriz.max()
valor_min = matriz.min()
posicion = matriz.argmax()
print(f"El valor maximo es: {valor_max}")
print(f"El valor minimo es: {valor_min}")
print(f"La posicion del maximo es: {posicion}")


El valor maximo es: 12
El valor minimo es: 1
La posicion del maximo es: 11


**P8.** Crea dos arreglos de 5 elementos con `np.random.randint` (valores entre 1 y 20).  
Súmalos, réstalos y multiplícalos elemento por elemento. Imprime cada resultado.

In [69]:
# Tu respuesta aquí
arreglo_1 = np.random.randint(1, 21, 5)
arreglo_2 = np.random.randint(1, 21, 5)

suma = arreglo_1 + arreglo_2
resta = arreglo_1 - arreglo_2
multi = arreglo_1 * arreglo_2

print(arreglo_1)
print(arreglo_2)
print(suma)
print(resta)
print(multi)

[ 9  9 20  8 18]
[ 6  5 13 16 15]
[15 14 33 24 33]
[ 3  4  7 -8  3]
[ 54  45 260 128 270]


**P9.** Dado el arreglo `notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])`,  
usa **indexación booleana** para obtener solo las notas mayores o iguales a 6. Imprime el resultado.

In [84]:
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])

# Tu respuesta aquí
booleano = notas >= 6
notas_aprobadas = notas[booleano]
print(notas)
print(booleano)
print(notas_aprobadas)

[ 8.5  6.   9.2  4.3  7.8  5.5 10.   3.1]
[ True  True  True False  True False  True False]
[ 8.5  6.   9.2  7.8 10. ]
